(define (run-example-test)
  (let ((expected 34) (actual (+ (* 3 10) 4)))
    (if (= expected actual)
      (begin (display "Test passed!\n") #t)
      (begin (display "Test failed!\n") #f)
    )
  )
)

(define (main) 
  (if (run-example-test) 
    (exit 0) 
    (exit 1) 
  )
)

(main)
