name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Chez Scheme build
        id: cache-chezscheme
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/scheme
            /usr/local/bin/petite
            /usr/local/lib/csv*
          key: ${{ runner.os }}-chezscheme-v10.1.0
          restore-keys: |
            ${{ runner.os }}-chezscheme-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget tar build-essential gcc libncurses-dev libx11-dev

      - name: Download and Build Chez Scheme
        if: steps.cache-chezscheme.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/cisco/ChezScheme/releases/download/v10.1.0/csv10.1.0.tar.gz
          tar -xzf csv10.1.0.tar.gz
          cd csv10.1.0
          ./configure
          make
          sudo make install

      - name: Run tests
        run: |
          make test